#### Mean -> Mean is an Arithmetic Average of some data  

##### Ex mean=Sum of all values/ number of all values

In [ ]:
import pandas as pd
import numpy as np

In [8]:
sal=[110,70,86,65,70,80,90,100,5000] # sal is a list containing the salary data in list fomat 

def cal_mean(data):  # here we have created a function to calculate the mean of the data
    return sum(data)/len(data)  # here we have taken the sum of the data and divided it by the length of the data 



manual_mean=cal_mean(sal) # here we have called the function and pased the sal data and storing it in a var 
print("Manual Mean:",manual_mean) # Printing the output of the mean calculated manually

Manual Mean: 630.1111111111111

In [9]:
df =pd.DataFrame({"Salary":sal})

mean_sal=df["Salary"].mean()
print(mean_sal)

630.1111111111111

In [13]:
sal_num=[110,70,86,65,70,80,90,100] # here we have removed the skewed data or outlier  ie 5000
print(np.mean(sal_num))
print(np.mean(sal))

83.875
630.1111111111111

#### When to use Mean :
    1. When the data is distributed normally (bell curve)
    2. No extreme outliers or extreme values 
    3. The data should be continuous 
#### When you should'nt use Mean 
    1. When the data is Skewed
    2. When the outliers exist or extreme values exist

#### Median - Median is the middle value when the data is sorted 
##### 1. sort the data 
##### 2. if odd count - middle value will be the median 
##### 3. if even count - average of the two middle values will be the median

In [15]:
marks=[110,70,86,65,70,80,90,100,5000] # skewed data or outlier  ie 5000

mrk=[110,70,86,65,70,80,90,100] # cleaned data without outlier

In [ ]:
def cal_median(data):
    srt_data=sorted(data) # here sorted will sort the list in ascending order and return a new list 
    n=len(srt_data)
    if n%2==0:
        median=(srt_data[n//2-1]+srt_data[n//2])/2
    else:
        median=srt_data[n//2]
    return median



manual_median=cal_median(marks)
print("Manual Median:",manual_median)
print("Numpy Median with outlier:",np.median(mrk))

Manual Median: 86
Numpy Median with outlier: 83.0

In [19]:
# Calculating the median using Numpy 
print("Median with outlier:",np.median(marks))
print("Median without outlier:",np.median(mrk))

Median with outlier: 86.0
Median without outlier: 83.0

In [23]:
# Calculating the Median Using Pandas 

data=pd.DataFrame({"Marks":marks})
skwdmdn=data["Marks"].median()
print("Pandas Median with outlier:",skwdmdn)

normalmdn=pd.DataFrame({"Marks":mrk})
print("Pandas Median without outlier:",normalmdn["Marks"].median())

Pandas Median with outlier: 86.0
Pandas Median without outlier: 83.0

#####  When to use Median
#### 1. When the data is Skewed 
#### 2. when the outliers present in the data 
#### 3. used for income,house price,or any other monetary data 
#### 4. when you are working with ordinal Data 
#### 5. when you are unsure about the distribution of the data

#### Mode 
##### Mode is the most frequent value in the data set.  its a measure of central tendency that works for the categoical data

In [24]:
from scipy import stats
from collections import Counter

In [35]:
scores=[85,90,92,85,88,85,95,90,85,88,90,81,90,81,90,85]

def cal_mode(data):
    counter=Counter(data)
    maxdata=max(counter.values())
    modes=[k for k,v in counter.items() if v==maxdata]
    return modes,maxdata


manual_mode,frequency=cal_mode(scores)
print("Manual Mode:",manual_mode)
print("Frequency of Mode:",frequency)

Manual Mode: [85, 90]
Frequency of Mode: 5

In [36]:
# Scipy Way of MOde Calcuation 

mode_data=stats.mode(scores)
mode_data

ModeResult(mode=np.int64(85), count=np.int64(5))

In [37]:
# Pandas Way of Mode Calculation

data=pd.DataFrame({"Scores":scores})
mode_data=data["Scores"].mode()
print("Pandas Mode:",mode_data.tolist())

Pandas Mode: [85, 90]

#### Types of Modes in Real Data 
##### Unimodal - Having only one mode value 
##### Bimodal  - Having two mode values 
##### MultiModal - Having more than two modes 
##### NoModeValue- Having no modes means each value is unique

#### When to use Mode 
##### 1. This is best used with categorical data 
##### 2. Finding the most common category 
##### 3. Discrete data analysis
##### 4. To understand the data distribution peaks 
##### 5. Its not useful when the data with unique values 
##### 6. It becomes less informative with many modes

### Label Encoding 
#### This is the way to teach Machines how to read categories

In [ ]:

# Below is list of colors and ML algos will not be able to read this 
data=["Red","Blue","Green","Red","Yellow","Blue","Red"]


enc_data=[0,1,2,0,3,1,0] # here we have encoded the data in numerical format so that ML algos can read this data and make predictions on it

#### Types of Categorical Data 
##### 1. Nominal Data  - No inherent order/ Unordered 
        color=["Red","Green","Yellow","Blue","Orange","Green"]
        countries=["India","Russia","USA","Nepal","SriLanka"]

##### 2. Ordinal Data - Has meaningful order 
        edu=["HighSchool","Graduation","PHD","Masters","Bachelors","Intermediate"]
        ratings=["Poor","Good","Average","VeryGood","Excellent"]

In [39]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [ ]:
data=pd.DataFrame({"Colors":["Red","Blue","Green","Magenta","Yellow","Blue","Red","Orange","Purple","Magenta","Purple","Magenta"],
                })

print("The data That we are having  is as follows ")
data

The data That we are having

     Colors
0       Red
1      Blue
2     Green
3   Magenta
4    Yellow
5      Blue
6       Red
7    Orange
8    Purple
9   Magenta
10   Purple
11  Magenta

In [68]:
ob=LabelEncoder() 

data["Encoded Colors"]=ob.fit_transform(data["Colors"])

print("After Label Encoding the data looks like this ")

print(dict(zip(ob.classes_,range(len(ob.classes_)))))
data

After Label Encoding the data looks like this
{'Blue': 0, 'Green': 1, 'Magenta': 2, 'Orange': 3, 'Purple': 4, 'Red': 5, 'Yellow': 6}

     Colors  Encoded Colors
0       Red               5
1      Blue               0
2     Green               1
3   Magenta               2
4    Yellow               6
5      Blue               0
6       Red               5
7    Orange               3
8    Purple               4
9   Magenta               2
10   Purple               4
11  Magenta               2

In [60]:
d1=["A","B","C","D"]
d2=[100,200,300,400]

print(dict(zip(d2,d1)))

{100: 'A', 200: 'B', 300: 'C', 400: 'D'}

In [70]:
fruits=["Apple","Banana","Orange"]

le=LabelEncoder()
enc_fruits=le.fit_transform(fruits)
print("Encoded Fruits:",enc_fruits.tolist())

Encoded Fruits: [0, 1, 2]

#### OneHotEncoding 
One Hot Encoding Creates binary columns for each category

In [76]:
myData=pd.DataFrame({"color":["Red","Blue","Green","Blue","Red","Magenta","Magenta","Yellow"],
                     "size":["Small","Medium","Large","Medium","Small","Large","Large","Medium"],
                     "price":[10,20,30,20,10,15,25,20]})
myData

     color    size  price
0      Red   Small     10
1     Blue  Medium     20
2    Green   Large     30
3     Blue  Medium     20
4      Red   Small     10
5  Magenta   Large     15
6  Magenta   Large     25
7   Yellow  Medium     20

In [79]:
#Pandas For OnHotENcoding 

datas=pd.get_dummies(myData,columns=["color","size"],prefix=["col","siz"])
datas

,price,col_Blue,col_Green,col_Magenta,col_Red,col_Yellow,siz_Large,siz_Medium,siz_Small
0,10,False,False,False,True,False,False,False,True
1,20,True,False,False,False,False,False,True,False
2,30,False,True,False,False,False,True,False,False
3,20,True,False,False,False,False,False,True,False
4,10,False,False,False,True,False,False,False,True
5,15,False,False,True,False,False,True,False,False
6,25,False,False,True,False,False,True,False,False
7,20,False,False,False,False,True,False,True,False

In [81]:

data=pd.DataFrame({
    "Fruits":["Apple","Banana","Orange","Apple","Banana"],
    "Size":["Small","Medium","Large","Small","Medium"],
    "Price":[10,20,30,10,20]
})
data

   Fruits    Size  Price
0   Apple   Small     10
1  Banana  Medium     20
2  Orange   Large     30
3   Apple   Small     10
4  Banana  Medium     20

#### Price - Price is the numeric value that the ML Algo can understand 
#### Size  - That is in text format that cant be understood by the ML algo 
#### Fruits - That is in Text format that also cant be understood by the ML Algos

In [82]:
encData=pd.get_dummies(data,columns=["Fruits"],prefix=["Frt"],dtype=int)
encData

     Size  Price  Frt_Apple  Frt_Banana  Frt_Orange
0   Small     10          1           0           0
1  Medium     20          0           1           0
2   Large     30          0           0           1
3   Small     10          1           0           0
4  Medium     20          0           1           0

In [83]:
encdata2=pd.get_dummies(data,columns=["Size"],prefix=["Sz"],dtype=int)
encdata2

   Fruits  Price  Sz_Large  Sz_Medium  Sz_Small
0   Apple     10         0          0         1
1  Banana     20         0          1         0
2  Orange     30         1          0         0
3   Apple     10         0          0         1
4  Banana     20         0          1         0

In [86]:
encode_data=pd.get_dummies(data,columns=["Fruits","Size"],prefix=["Frt","Sz"],dtype=int)
encode_data

   Price  Frt_Apple  Frt_Banana  Frt_Orange  Sz_Large  Sz_Medium  Sz_Small
0     10          1           0           0         0          0         1
1     20          0           1           0         0          1         0
2     30          0           0           1         1          0         0
3     10          1           0           0         0          0         1
4     20          0           1           0         0          1         0

In [102]:
from sklearn.preprocessing import OneHotEncoder

obj=OneHotEncoder()
data=pd.DataFrame({
    "Fruits":["Apple","Banana","Orange","Apple","Banana"],
    "Size":["Small","Medium","Large","Small","Medium"],
    "Price":[10,20,30,10,20]
})


# Here we have encoded the data using Onehotencoder 
encoded_data=obj.fit_transform(data[["Fruits","Size"]])

encoded_data.toarray() # here we are getting an array in encoded format 


# here we are extratcing  the fearure names or the newly created columns after encoding the data
feature_names=obj.get_feature_names_out(["Fruits","Size"])
feature_names

final_data=pd.DataFrame(encoded_data.toarray(),columns=feature_names)
final_data["New Price"]=data["Price"]
final_data

,Fruits_Apple,Fruits_Banana,Fruits_Orange,Size_Large,Size_Medium,Size_Small,New Price
0,1.0,0.0,0.0,0.0,0.0,1.0,10
1,0.0,1.0,0.0,0.0,1.0,0.0,20
2,0.0,0.0,1.0,1.0,0.0,0.0,30
3,1.0,0.0,0.0,0.0,0.0,1.0,10
4,0.0,1.0,0.0,0.0,1.0,0.0,20