In [41]:
import pandas as pd 
import numpy as np

In [42]:
df=pd.read_csv("iris.csv") # this iris.csv is stored in my folder 
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [32]:
from  sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [17]:
df.columns.tolist()

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [ ]:
X=df[["sepal_length",'sepal_width','petal_length','petal_width']]
X # Features

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
Y=df['species']
Y  # Response

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [53]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=45,test_size=0.2)

In [55]:
mymodel=DecisionTreeClassifier() ## here we have created the object of This class 


mymodel.fit(x_train,y_train) #using the object of Decision class ie mymodel
# we can call the methods of that class so here we have  called the method 
# fit to train the model 
# once it is ready it predict anything

DecisionTreeClassifier()

In [60]:
y_pred=mymodel.predict(x_test) # y_pred is new variable 
y_pred.tolist()
print(y_test)
print(y_pred.tolist())

0          setosa
43         setosa
129     virginica
3          setosa
34         setosa
44         setosa
38         setosa
105     virginica
123     virginica
140     virginica
28         setosa
125     virginica
113     virginica
103     virginica
133     virginica
35         setosa
145     virginica
142     virginica
40         setosa
87     versicolor
84     versicolor
85     versicolor
115     virginica
51     versicolor
4          setosa
112     virginica
92     versicolor
64     versicolor
10         setosa
91     versicolor
Name: species, dtype: object
['setosa', 'setosa', 'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'virginica', 'virginica', 'virginica', 'setosa', 'virginica', 'virginica', 'virginica', 'versicolor', 'setosa', 'virginica', 'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor']

In [62]:
modacc=accuracy_score(y_test,y_pred)
modacc*100

96.66666666666667

In [63]:
flower=[[4.5,2.3,5.2,2.4]]

res=mymodel.predict(flower)
res

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['virginica'], dtype=object)