In [717]:
import numpy as np  # import statement for numpy library

In [718]:
arr=np.array([1,2,3,4,5]) 
type(arr)

numpy.ndarray

In [719]:
twodarr=np.array([[75,8,9],[10,11,12]])
print(twodarr.shape) # shape is a tuple representing the dimensions of the array
print(twodarr.ndim) # ndim is the number of dimensions of the array
print(twodarr.size) # size is the total number of elements in the array
print(twodarr.itemsize) # itemsize is the size in bytes of each element in the array
print(twodarr.dtype) # dtype is the data type of the elements in the array
print(twodarr.nbytes) # nbytes is the total number of bytes consumed by the elements of the array
print(twodarr.strides) # strides is the number of bytes to step in each dimension when traversing an array

(2, 3)
2
6
8
int64
48
(24, 8)

In [720]:
myarr=np.array([12,7,8,9,12],dtype='int64') 
myarr

array([12,  7,  8,  9, 12])

#### DataType Conversion in Numpy

In [721]:
arr2=np.array([12.5,6.89,9.84,6.78],dtype='float32')


arr3=arr2.astype('int64')

arr3

array([12,  6,  9,  6])

### Creation of Array Using inbuilt Functions

In [722]:
x=np.zeros([5,3,2])  # This will create a 3D array of shape (5, 3, 2) filled with zeros also called Tensor 
x2=np.ones(4)
x3=np.identity(4)
x4=np.eye(4,k=1)
x4

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [723]:
ar=np.arange(10,2,-1)
ar

array([10,  9,  8,  7,  6,  5,  4,  3])

#### Slicing in Arrays

#### Boolean Indexing

In [724]:
darr=np.array([15,22,30,8,45,12,60])

mask=darr>25

print(mask)

[False False  True False  True False  True]

##### I want to print the items which are either  lesser than 20 or  greater than 50

In [725]:
m2=(darr<20) | (darr>50)
print(darr[m2])

[15  8 12 60]

#### Conditional Statements

In [726]:
narr=np.array([10,45,25,30,45,50])

res=np.where(narr<20,"Small",np.where(narr<40,"Medium","Large"))
print(res)

['Small' 'Large' 'Medium' 'Medium' 'Large' 'Large']

#### Numpy Select function

In [727]:
narr=np.array([10,45,25,30,45,50])

cons=[narr<20,
      (narr>=20)&(narr<40),
      narr>=40]

sel=["small","medium","Large"]
res=np.select(cons,sel,default="Unknown")
print(res)

['small' 'Large' 'medium' 'medium' 'Large' 'Large']

### Arrays Reshape

In [728]:
npar=np.arange(12)
rs=npar.reshape(4,-1)
print(rs)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

In [729]:
npr=np.arange(2,20,2)

npr=npr.reshape(3,3)

print(npr.flatten())

[ 2  4  6  8 10 12 14 16 18]

#### Pandas Series 
###### Series is a smart dictionary that wears a mask of Numpy Array 

###### Series contains mainly three things 
 1. Value - The actual data ( this is soed as numpy array )
 2. index - The labels (This can be said as primary key )
 3. Name - The coumn heading

In [730]:
import pandas as pd 
import numpy as np

In [731]:
s=pd.Series([8,9,7,6,5],index=["Lko","vadodara","delhi","mumbai","kolkata"],name="City")

print(s)

Lko         8
vadodara    9
delhi       7
mumbai      6
kolkata     5
Name: City, dtype: int64

In [732]:
print(s.name) 
print(s.index )
print(s.values)
print(s.dtype)

City
Index(['Lko', 'vadodara', 'delhi', 'mumbai', 'kolkata'], dtype='object')
[8 9 7 6 5]
int64

In [733]:
print(s.iloc[1])
print(s["delhi"])

9
7

In [734]:
s2=pd.Series([1,2,3,4])
print(s2)

0    1
1    2
2    3
3    4
dtype: int64

In [735]:
s2.iloc[0]=None
print(s2)

0    NaN
1    2.0
2    3.0
3    4.0
dtype: float64

In [736]:
s3=pd.Series([1,2,3,4],dtype='Int64')
s3.iloc[0]=pd.NA
print(s3)

0    <NA>
1       2
2       3
3       4
dtype: Int64

In [737]:
s4=pd.Series([10,20,30],index=['a','b','c'])
print(id(s4))
sdrop=s4.drop('b') # its creating a new series without 'b' and its value
print(sdrop)

print(s4)

1641110868640
a    10
c    30
dtype: int64
a    10
b    20
c    30
dtype: int64

## Vectorization

In [738]:
import numpy as np 
import time

In [739]:
mylist=list(range(1000000))

start=time.time()
total=0
for i in mylist:
    total=total+i
print("Time taken by the list is ",time.time()-start)

Time taken by the list is  0.5052378177642822

In [740]:
nparr=np.arange(1000000)
start=time.time()
total=0
total=np.sum(nparr)
print("Time taken by the numpy array is ",time.time()-start)

Time taken by the numpy array is  0.0009961128234863281

#### Pandas

In [741]:
import pandas as pd
import numpy as np

In [742]:
d ={
    "name":["Alice","Bob","Charlie","David","rohit","agastya","amar","joy"],
     "age":[25,30,35,40,50,21,43,45],
     "city":["New York","Los Angeles","Chicago","Houston","hongkong","delhi","mumbai","kolkata"],
     "sal":[50000,60000,70000,80000,30000,32000,45000,870000]
     }

df=pd.DataFrame(d)
df

      name  age         city     sal
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4    rohit   50     hongkong   30000
5  agastya   21        delhi   32000
6     amar   43       mumbai   45000
7      joy   45      kolkata  870000

In [743]:
for i in range(len(df)):
    df.loc[i,"sal"]=df.loc[i,"sal"]*1.0

df

      name  age         city     sal
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4    rohit   50     hongkong   30000
5  agastya   21        delhi   32000
6     amar   43       mumbai   45000
7      joy   45      kolkata  870000

In [744]:
df["sal"]=df["sal"]*1.0
df

      name  age         city       sal
0    Alice   25     New York   50000.0
1      Bob   30  Los Angeles   60000.0
2  Charlie   35      Chicago   70000.0
3    David   40      Houston   80000.0
4    rohit   50     hongkong   30000.0
5  agastya   21        delhi   32000.0
6     amar   43       mumbai   45000.0
7      joy   45      kolkata  870000.0

In [745]:

df.loc[df["sal"]>50000,"age"]-=5
df

      name  age         city       sal
0    Alice   25     New York   50000.0
1      Bob   25  Los Angeles   60000.0
2  Charlie   30      Chicago   70000.0
3    David   35      Houston   80000.0
4    rohit   50     hongkong   30000.0
5  agastya   21        delhi   32000.0
6     amar   43       mumbai   45000.0
7      joy   40      kolkata  870000.0

In [746]:
data={
    "players":["virat","Rohit","sehwag","dhoni","virat","Rohit","sehwag","dhoni"],
    "matches":[100,200,300,400,100,200,300,400],
    "runs":[154,200,123,257,309,198,171,120],
    "Balls":[50,100,120,120,150,80,120,100]
}
ipl=pd.DataFrame(data)
ipl

  players  matches  runs  Balls
0   virat      100   154     50
1   Rohit      200   200    100
2  sehwag      300   123    120
3   dhoni      400   257    120
4   virat      100   309    150
5   Rohit      200   198     80
6  sehwag      300   171    120
7   dhoni      400   120    100

## Task 
1. FInd the Strike rate of Each player    (run/ball*100)
2. Show only matches where virat has scored more than 150
3. show the total runs scored by the player and highest score by the player

In [747]:
data={
    "players":["virat","Rohit","sehwag","dhoni","virat","Rohit","virat","dhoni"],
    "matches":[25,123,89,15,108,170,111,20],
    "runs":[154,200,123,257,309,198,171,54],
    "Balls":[50,100,120,120,150,80,120,100]
}
df=pd.DataFrame(data)
df

  players  matches  runs  Balls
0   virat       25   154     50
1   Rohit      123   200    100
2  sehwag       89   123    120
3   dhoni       15   257    120
4   virat      108   309    150
5   Rohit      170   198     80
6   virat      111   171    120
7   dhoni       20    54    100

### GroupBy

In [748]:
grp=df.groupby("players" )["runs"].sum()
grp

players
Rohit     398
dhoni     311
sehwag    123
virat     634
Name: runs, dtype: int64

### Aggregation

In [749]:
summ=df.groupby("players").agg(
    Total_runs=("runs", "sum"),
    Average_runs=("runs", "mean"),
    Matches_played=("matches","sum"),
    Highest_score=("runs","max"),
    Lowest_score=("runs","min"),
    Totals_balls=("Balls","sum")
).reset_index()

summ

,players,Total_runs,Average_runs,Matches_played,Highest_score,Lowest_score,Totals_balls
0,Rohit,398,199.000000,293,200,198,180
1,dhoni,311,155.500000,35,257,54,220
2,sehwag,123,123.000000,89,123,123,120
3,virat,634,211.333333,244,309,154,320

In [750]:
summ=df.groupby("players").agg(
    Total_runs=("runs", "sum"),
    Average_runs=("runs", "mean"),
    Matches_played=("matches","sum"),
    Highest_score=("runs","max"),
    Lowest_score=("runs","min"),
    Totals_balls=("Balls","sum"),
    Fifties=("runs",lambda x:((x>=50) & (x<100)).sum())
).reset_index()
summ

,players,Total_runs,Average_runs,Matches_played,Highest_score,Lowest_score,Totals_balls,Fifties
0,Rohit,398,199.000000,293,200,198,180,0
1,dhoni,311,155.500000,35,257,54,220,1
2,sehwag,123,123.000000,89,123,123,120,0
3,virat,634,211.333333,244,309,154,320,0

#### Pandas In python

In [751]:
# Date 28 May 2026 
import pandas as pd 
import numpy as np

In [752]:
df=pd.DataFrame({
    "Name":["Rahul","Joy","Kumar","Mahi","Jhanvi","Shubham","Priya","Anit"],
     "age":[25,30,35,40,50,21,43,45],
     "city":["mumbai","delhi","Chicago","kolkata","hongkong","delhi","mumbai","kolkata"],
     "sal":[50000,60000,70000,80000,30000,32000,45000,870000],
     "Experience":[2,5,7,10,15,1,8,20],
     "Department":["IT","HR","Finance","IT","HR","Finance","IT","HR"]
})
df

      Name  age      city     sal  Experience Department
0    Rahul   25    mumbai   50000           2         IT
1      Joy   30     delhi   60000           5         HR
2    Kumar   35   Chicago   70000           7    Finance
3     Mahi   40   kolkata   80000          10         IT
4   Jhanvi   50  hongkong   30000          15         HR
5  Shubham   21     delhi   32000           1    Finance
6    Priya   43    mumbai   45000           8         IT
7     Anit   45   kolkata  870000          20         HR

In [753]:
df["Department"]   # Both will return the Same Thing a single columns data
df.Department # this will also return the same thing that is the single column data

0         IT
1         HR
2    Finance
3         IT
4         HR
5    Finance
6         IT
7         HR
Name: Department, dtype: object

In [754]:
print(type(df["Name"]))  # This will return the Series 
print(type(df[["Name"]])) # This will return the DataFrame

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [755]:
df.loc[:,["Name","sal"]] # This will return DataFrame 
# This is Column Access or can sal Label based Access

      Name     sal
0    Rahul   50000
1      Joy   60000
2    Kumar   70000
3     Mahi   80000
4   Jhanvi   30000
5  Shubham   32000
6    Priya   45000
7     Anit  870000

In [756]:
df.iloc[:,[0,5]] # This will return Name and Department  
df.iloc[:,0:3] # This will three coluns Name age and City in dataFrame format

      Name  age      city
0    Rahul   25    mumbai
1      Joy   30     delhi
2    Kumar   35   Chicago
3     Mahi   40   kolkata
4   Jhanvi   50  hongkong
5  Shubham   21     delhi
6    Priya   43    mumbai
7     Anit   45   kolkata

### Now we are going to access rows Using .iloc method

In [757]:
print(df.iloc[[4,2]])

     Name  age      city    sal  Experience Department
4  Jhanvi   50  hongkong  30000          15         HR
2   Kumar   35   Chicago  70000           7    Finance

In [758]:
df.iloc[0:3,0:4]

    Name  age     city    sal
0  Rahul   25   mumbai  50000
1    Joy   30    delhi  60000
2  Kumar   35  Chicago  70000

##### I want to print 0th and 1st row and 0th and 3rd column what should i write to get it printed

In [759]:
df.iloc[[0,1],[0,3]]

    Name    sal
0  Rahul  50000
1    Joy  60000

#### We are Going to Use .loc function to get the rows printed

In [760]:
print(df.loc[[0,2,3]])
print("Second output")
print(df.loc[3])

    Name  age     city    sal  Experience Department
0  Rahul   25   mumbai  50000           2         IT
2  Kumar   35  Chicago  70000           7    Finance
3   Mahi   40  kolkata  80000          10         IT
Second output
Name             Mahi
age                40
city          kolkata
sal             80000
Experience         10
Department         IT
Name: 3, dtype: object

In [761]:
df2=df.set_index("Name")
df2

         age      city     sal  Experience Department
Name
Rahul     25    mumbai   50000           2         IT
Joy       30     delhi   60000           5         HR
Kumar     35   Chicago   70000           7    Finance
Mahi      40   kolkata   80000          10         IT
Jhanvi    50  hongkong   30000          15         HR
Shubham   21     delhi   32000           1    Finance
Priya     43    mumbai   45000           8         IT
Anit      45   kolkata  870000          20         HR

In [762]:
df2.loc[["Jhanvi","Priya"]]

        age      city    sal  Experience Department
Name
Jhanvi   50  hongkong  30000          15         HR
Priya    43    mumbai  45000           8         IT

#### Here we are going to Use .loc function to get rows+columns together

In [763]:
# Syntax  : df.loc[rows_selection,col_selection]

df.loc[3,"sal"]  # here we are accessing specific row and specific col

# Now multiple rows  and single column

df.loc[0:3,["Name","age","Department"]]

df.loc[df["age"]>25,["Name","sal","age","Department"]]# simple way 
mask=df["age"]>25
df.loc[mask,["Name","sal","age","Department"]] # here we are using Masking

     Name     sal  age Department
1     Joy   60000   30         HR
2   Kumar   70000   35    Finance
3    Mahi   80000   40         IT
4  Jhanvi   30000   50         HR
6   Priya   45000   43         IT
7    Anit  870000   45         HR

In [764]:
df[(df["age"]>25) & (df["sal"]>50000)],[["Name","sal","age","Department"]] # here we are using multiple conditions
# This is doubtful syntax but it is correct and it will work fine

(    Name  age     city     sal  Experience Department
 1    Joy   30    delhi   60000           5         HR
 2  Kumar   35  Chicago   70000           7    Finance
 3   Mahi   40  kolkata   80000          10         IT
 7   Anit   45  kolkata  870000          20         HR,
 [['Name', 'sal', 'age', 'Department']])

#### Query method like sql

In [765]:
df.query("age>25 and sal>50000 and Department=='IT'") # this is query method to filter the data based on conditions

   Name  age     city    sal  Experience Department
3  Mahi   40  kolkata  80000          10         IT

In [766]:
df.query("age>25 and sal>30000 and city in ['Chicago','mumbai']")

    Name  age     city    sal  Experience Department
2  Kumar   35  Chicago  70000           7    Finance
6  Priya   43   mumbai  45000           8         IT

@var way to write the queries 

con=30  # here we have taken a var and we will use this in query method by using @symbol to refer the var 
df.query("age>@con and sal>30000 and city in ['Chicago','mumbai']")

In [767]:
con=30  # here we have taken a var and we will use this in query method by using @symbol to refer the var 
df.query("age>@con and sal>30000 and city in ['Chicago','mumbai']")

    Name  age     city    sal  Experience Department
2  Kumar   35  Chicago  70000           7    Finance
6  Priya   43   mumbai  45000           8         IT

#### isin() method   this is like membership method

In [768]:
df[df["city"].isin(["delhi","mumbai"])]

      Name  age    city    sal  Experience Department
0    Rahul   25  mumbai  50000           2         IT
1      Joy   30   delhi  60000           5         HR
5  Shubham   21   delhi  32000           1    Finance
6    Priya   43  mumbai  45000           8         IT

### between() - Range Checking

In [769]:
# Age should be greater than 30 and less than 40 

df[df["age"].between(30,40)][["Name","Department"]]

    Name Department
1    Joy         HR
2  Kumar    Finance
3   Mahi         IT

#### 1. to print only sal and Name cols 
#### 2. show the data whose age>40 
#### 3. display the row no 2 3 4 using .iloc()
#### 4. show only first 4 rows of Name and Department cols 
#### 5. Show all the names where the department is IT 
#### 6. Show the first two cols of last 3 rows 
#### 7. show the data where the sal is between 60k to 80k along with the name and city cols

#### Goupby()

In [770]:
df.groupby("city")['sal'].mean()

city
Chicago      70000.0
delhi        46000.0
hongkong     30000.0
kolkata     475000.0
mumbai       47500.0
Name: sal, dtype: float64

In [771]:
df.groupby("Department")["sal"].agg(['min','max','mean','sum','count'])

              min     max           mean     sum  count
Department
Finance     32000   70000   51000.000000  102000      2
HR          30000  870000  320000.000000  960000      3
IT          45000   80000   58333.333333  175000      3

In [772]:
df.agg({'age':['min','max','mean'],
        'sal':['min','max','std'],
        'Experience':['min','max','median']
        })

           age            sal  Experience
min     21.000   30000.000000         1.0
max     50.000  870000.000000        20.0
mean    36.125            NaN         NaN
std        NaN  289575.520621         NaN
median     NaN            NaN         7.5

#### Sorting + EDA (Exploratory Data Analysis)

In [773]:
# sort_values() this is the functions to sort the things 
# it has multiple params like by,ascending,inplace etc

df.sort_values("Name",ascending=False)

      Name  age      city     sal  Experience Department
5  Shubham   21     delhi   32000           1    Finance
0    Rahul   25    mumbai   50000           2         IT
6    Priya   43    mumbai   45000           8         IT
3     Mahi   40   kolkata   80000          10         IT
2    Kumar   35   Chicago   70000           7    Finance
1      Joy   30     delhi   60000           5         HR
4   Jhanvi   50  hongkong   30000          15         HR
7     Anit   45   kolkata  870000          20         HR

In [774]:
df.sort_values(["Department","sal"],ascending=[True,False])

      Name  age      city     sal  Experience Department
2    Kumar   35   Chicago   70000           7    Finance
5  Shubham   21     delhi   32000           1    Finance
7     Anit   45   kolkata  870000          20         HR
1      Joy   30     delhi   60000           5         HR
4   Jhanvi   50  hongkong   30000          15         HR
3     Mahi   40   kolkata   80000          10         IT
0    Rahul   25    mumbai   50000           2         IT
6    Priya   43    mumbai   45000           8         IT

In [775]:
df['sal_rank']=df['sal'].rank(ascending=False)
df

      Name  age      city     sal  Experience Department  sal_rank
0    Rahul   25    mumbai   50000           2         IT       5.0
1      Joy   30     delhi   60000           5         HR       4.0
2    Kumar   35   Chicago   70000           7    Finance       3.0
3     Mahi   40   kolkata   80000          10         IT       2.0
4   Jhanvi   50  hongkong   30000          15         HR       8.0
5  Shubham   21     delhi   32000           1    Finance       7.0
6    Priya   43    mumbai   45000           8         IT       6.0
7     Anit   45   kolkata  870000          20         HR       1.0

#### EDA - its the process to understand the data without assumptions 
##### Responsibilty of Analyst is to:
1.  understand the data 
2. Find the pattern 
3. To find the problems in the data

In [776]:
df.head() # it will show by default first 5 rows of the data 
df.tail() # it will show by default last 5 rows of the data

df.sample(3) # it will return random sample of the data by default it will return 1 row of the data
df.sample(frac=0.5) # it will return random sample of the data by default it will return 50% of the data because we have given frac=0.5

      Name  age      city    sal  Experience Department  sal_rank
0    Rahul   25    mumbai  50000           2         IT       5.0
5  Shubham   21     delhi  32000           1    Finance       7.0
3     Mahi   40   kolkata  80000          10         IT       2.0
4   Jhanvi   50  hongkong  30000          15         HR       8.0

In [777]:
df.shape # it will return the shape of the data in tuple format (rows,columns)
df.info() # it will return the info of the data like number of non-null values in each column and data types of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   age         8 non-null      int64
 2   city        8 non-null      object
 3   sal         8 non-null      int64
 4   Experience  8 non-null      int64
 5   Department  8 non-null      object
 6   sal_rank    8 non-null      float64
dtypes: float64(1), int64(3), object(3)
memory usage: 576.0+ bytes

In [778]:
df.dtypes

Name           object
age             int64
city           object
sal             int64
Experience      int64
Department     object
sal_rank      float64
dtype: object

In [779]:
num_cols=df.select_dtypes(include=['int64','float64']).columns
num_cols
cat_col=df.select_dtypes(include=['object']).columns

print("Numerical columns:",len(list(num_cols)),"Categorical columns:",len(list(cat_col)))

Numerical columns: 4 Categorical columns: 3

In [780]:
df['age']=df['age']*1.0
df['age']=df['age'].astype('float64')

df

      Name   age      city     sal  Experience Department  sal_rank
0    Rahul  25.0    mumbai   50000           2         IT       5.0
1      Joy  30.0     delhi   60000           5         HR       4.0
2    Kumar  35.0   Chicago   70000           7    Finance       3.0
3     Mahi  40.0   kolkata   80000          10         IT       2.0
4   Jhanvi  50.0  hongkong   30000          15         HR       8.0
5  Shubham  21.0     delhi   32000           1    Finance       7.0
6    Priya  43.0    mumbai   45000           8         IT       6.0
7     Anit  45.0   kolkata  870000          20         HR       1.0

In [781]:
df.describe(include="all")

,Name,age,city,sal,Experience,Department,sal_rank
count,8,8.000000,8,8.000000,8.000000,8,8.00000
unique,8,NaN,5,NaN,NaN,3,NaN
top,Rahul,NaN,mumbai,NaN,NaN,IT,NaN
freq,1,NaN,2,NaN,NaN,3,NaN
mean,NaN,36.125000,NaN,154625.000000,8.500000,NaN,4.50000
std,NaN,10.176128,NaN,289575.520621,6.436503,NaN,2.44949
min,NaN,21.000000,NaN,30000.000000,1.000000,NaN,1.00000
25%,NaN,28.750000,NaN,41750.000000,4.250000,NaN,2.75000
50%,NaN,37.500000,NaN,55000.000000,7.500000,NaN,4.50000
75%,NaN,43.500000,NaN,72500.000000,11.250000,NaN,6.25000
max,NaN,50.000000,NaN,870000.000000,20.000000,NaN,8.00000

In [782]:

print(df['city'].value_counts(normalize=True)*100 )# it will return the count of each unique value in the city column and normalize=True will return the percentage of each unique value in the city column

print(df['city'].value_counts())# it will return the count of each unique value in the city column without normalizing it to percentage

city
mumbai      25.0
delhi       25.0
kolkata     25.0
Chicago     12.5
hongkong    12.5
Name: proportion, dtype: float64
city
mumbai      2
delhi       2
kolkata     2
Chicago     1
hongkong    1
Name: count, dtype: int64

In [783]:
import pandas as pd 
import numpy as np

df=pd.DataFrame({
    "Name":["Rahul","Joy","Kumar","Mahi","Jhanvi","Shubham","Priya","Anit"],
     "age":[25,np.nan,35,40,50,np.nan,43,45],
     "city":["mumbai","delhi","Chicago","kolkata","hongkong","delhi",np.nan,"kolkata"],
     "sal":[50000,60000,70000,80000,30000,32000,45000,870000],
     "Experience":[2,5,7,np.nan,15,1,8,np.nan],
     "Department":["IT","HR","Finance",np.nan,"HR","Finance","IT","HR"]
})

df

      Name   age      city     sal  Experience Department
0    Rahul  25.0    mumbai   50000         2.0         IT
1      Joy   NaN     delhi   60000         5.0         HR
2    Kumar  35.0   Chicago   70000         7.0    Finance
3     Mahi  40.0   kolkata   80000         NaN        NaN
4   Jhanvi  50.0  hongkong   30000        15.0         HR
5  Shubham   NaN     delhi   32000         1.0    Finance
6    Priya  43.0       NaN   45000         8.0         IT
7     Anit  45.0   kolkata  870000         NaN         HR

In [784]:
df.isna().sum() # it will return the count of missing values in each column of the data frame

Name          0
age           2
city          1
sal           0
Experience    2
Department    1
dtype: int64

In [785]:
df.notnull().sum()

Name          8
age           6
city          7
sal           8
Experience    6
Department    7
dtype: int64

In [786]:
df.isna().mean()*100

Name           0.0
age           25.0
city          12.5
sal            0.0
Experience    25.0
Department    12.5
dtype: float64

In [787]:
df[df.isna().all(axis=1)] # it will return the rows which have at least one missing value in any column
df[df.isna().any(axis=1)] # it will return the rows which have at least one missing value in any column

      Name   age     city     sal  Experience Department
1      Joy   NaN    delhi   60000         5.0         HR
3     Mahi  40.0  kolkata   80000         NaN        NaN
5  Shubham   NaN    delhi   32000         1.0    Finance
6    Priya  43.0      NaN   45000         8.0         IT
7     Anit  45.0  kolkata  870000         NaN         HR

In [788]:
df[df["age"].isna()]

      Name  age   city    sal  Experience Department
1      Joy  NaN  delhi  60000         5.0         HR
5  Shubham  NaN  delhi  32000         1.0    Finance

In [789]:
# df.dropna() this function drops the rows or cols from the data set 



df

      Name   age      city     sal  Experience Department
0    Rahul  25.0    mumbai   50000         2.0         IT
1      Joy   NaN     delhi   60000         5.0         HR
2    Kumar  35.0   Chicago   70000         7.0    Finance
3     Mahi  40.0   kolkata   80000         NaN        NaN
4   Jhanvi  50.0  hongkong   30000        15.0         HR
5  Shubham   NaN     delhi   32000         1.0    Finance
6    Priya  43.0       NaN   45000         8.0         IT
7     Anit  45.0   kolkata  870000         NaN         HR

In [790]:
df.dropna(axis=1) # it will drop the columns which have less than 6 non-null values
df.dropna(axis=0) # it will drop the rows which have less than 6 non-null values

     Name   age      city    sal  Experience Department
0   Rahul  25.0    mumbai  50000         2.0         IT
2   Kumar  35.0   Chicago  70000         7.0    Finance
4  Jhanvi  50.0  hongkong  30000        15.0         HR

In [791]:
df["Experience"].fillna(0)
df["city"].fillna("Unknown")

df.fillna({"Experience":0,"city":"Unknown"})
df

      Name   age      city     sal  Experience Department
0    Rahul  25.0    mumbai   50000         2.0         IT
1      Joy   NaN     delhi   60000         5.0         HR
2    Kumar  35.0   Chicago   70000         7.0    Finance
3     Mahi  40.0   kolkata   80000         NaN        NaN
4   Jhanvi  50.0  hongkong   30000        15.0         HR
5  Shubham   NaN     delhi   32000         1.0    Finance
6    Priya  43.0       NaN   45000         8.0         IT
7     Anit  45.0   kolkata  870000         NaN         HR

#### Filling the empty values Statistically

In [792]:
df["Department"].fillna(df["Department"].mode()[0])

0         IT
1         HR
2    Finance
3         HR
4         HR
5    Finance
6         IT
7         HR
Name: Department, dtype: object

In [793]:
df.replace("Finance","FIna",inplace=True)
df

      Name   age      city     sal  Experience Department
0    Rahul  25.0    mumbai   50000         2.0         IT
1      Joy   NaN     delhi   60000         5.0         HR
2    Kumar  35.0   Chicago   70000         7.0       FIna
3     Mahi  40.0   kolkata   80000         NaN        NaN
4   Jhanvi  50.0  hongkong   30000        15.0         HR
5  Shubham   NaN     delhi   32000         1.0       FIna
6    Priya  43.0       NaN   45000         8.0         IT
7     Anit  45.0   kolkata  870000         NaN         HR

In [794]:
data=({
    "Student":["Alice","Bob","Charlie","David","rohit","agastya","amar","joy"],
     "maths":[85,90,np.nan,92,88,95,80,91],
     "science":[80,85,90,np.nan,88,92,np.nan,89],
     "English":[75,80,85,90,88,92,84,89],
     "Sanskrit":[70,75,np.nan,85,88,90,82,87],
     "Attendance":[90,85,95,80,88,np.nan,84,89]
})

## Task 
#### 1. Count the missing values 
#### 2. Fill all the missing values in maths with the mean value without using mean function 
#### 3. In english fill teh missing values with 0 
#### 4. verify whether your data is having any missing values or not 
#### 5. Fill the nan values in attendance column using mean value 
#### 6. remove that row which have more than 2 nan values

In [795]:
df=pd.DataFrame({
    "StudentId":["S001","S002","S003","S004","S005","S006","S007","S008","S009","S010","S011","S012","S013","S014","S015"],
    "Name":["Alice","Bob","Charlie","David","rohit","agastya","amar","joy","Rohit","Mahi","Jhanvi","Shubham","Priya","Anit","Rahul"],
    "Maths":[85,90,np.nan,92,88,95,80,91,89,94,87,90,85,88,92],
    "Science":[80,85,90,np.nan,88,92,np.nan,89,90,40,56,78,85,90,30],
    "English":[75,80,85,90,88,92,84,89,90,40,56,78,85,90,30],
    "Attendance":[90,85,95,80,88,np.nan,84,89,90,40,56,78,85,90,30],
    "Grade":["A","A","B","A",np.nan,"A","C",np.nan,"A","C","B","B","B","A","A"],
    "Phone":["8989657890","9876543210","7654321098","6543210987","5432109876","4321098765","3210987654","2109876543","1098765432","0987654321","9876543210","8765432109","7654321098","6543210987","5432109876"],
    "Email":["alice@example.com","bob@example.com","charlie@example.com","david@example.com","rohit@example.com","agastya@example.com","amar@example.com","joy@example.com","rohit@example.com","mahi@example.com","jhanvi@example.com","shubham@example.com","priya@example.com","anit@example.com","rahul@example.com"],
    "Remarks":["Excellent","Excellent","Good","Excellent","Good","Excellent","Average","Good","Excellent","Average","Good","Good","Good","Excellent","Excellent"]

})
df

,StudentId,Name,Maths,Science,English,Attendance,Grade,Phone,Email,Remarks
0,S001,Alice,85.0,80.0,75,90.0,A,8989657890,alice@example.com,Excellent
1,S002,Bob,90.0,85.0,80,85.0,A,9876543210,bob@example.com,Excellent
2,S003,Charlie,NaN,90.0,85,95.0,B,7654321098,charlie@example.com,Good
3,S004,David,92.0,NaN,90,80.0,A,6543210987,david@example.com,Excellent
4,S005,rohit,88.0,88.0,88,88.0,NaN,5432109876,rohit@example.com,Good
5,S006,agastya,95.0,92.0,92,NaN,A,4321098765,agastya@example.com,Excellent
6,S007,amar,80.0,NaN,84,84.0,C,3210987654,amar@example.com,Average
7,S008,joy,91.0,89.0,89,89.0,NaN,2109876543,joy@example.com,Good
8,S009,Rohit,89.0,90.0,90,90.0,A,1098765432,rohit@example.com,Excellent
9,S010,Mahi,94.0,40.0,40,40.0,C,0987654321,mahi@example.com,Average
10,S011,Jhanvi,87.0,56.0,56,56.0,B,9876543210,jhanvi@example.com,Good
11,S012,Shubham,90.0,78.0,78,78.0,B,8765432109,shubham@example.com,Good
12,S013,Priya,85.0,85.0,85,85.0,B,7654321098,priya@example.com,Good
13,S014,Anit,88.0,90.0,90,90.0,A,6543210987,anit@example.com,Excellent
14,S015,Rahul,92.0,30.0,30,30.0,A,5432109876,rahul@example.com,Excellent

In [796]:
df.notnull().sum()
df.describe(include="all")
# i want to print all the rows which are having atleast on missing value in any column
df[df.isnull().any(axis=1)]
# i want to check if in a column there is any missing value or not
df["Maths"].isnull()

df.drop("Maths",axis=1)
df["Total"]=df["Maths"]+df["Science"]+df["English"]

df.fillna({"Attendance":df["Attendance"].mean(),"Total":df["Total"].mean()})

df["Grade"].fillna(df["Grade"].mode()[0],inplace=True)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_5680\1413352406.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Grade"].fillna(df["Grade"].mode()[0],inplace=True)

,StudentId,Name,Maths,Science,English,Attendance,Grade,Phone,Email,Remarks,Total
0,S001,Alice,85.0,80.0,75,90.0,A,8989657890,alice@example.com,Excellent,240.0
1,S002,Bob,90.0,85.0,80,85.0,A,9876543210,bob@example.com,Excellent,255.0
2,S003,Charlie,NaN,90.0,85,95.0,B,7654321098,charlie@example.com,Good,NaN
3,S004,David,92.0,NaN,90,80.0,A,6543210987,david@example.com,Excellent,NaN
4,S005,rohit,88.0,88.0,88,88.0,A,5432109876,rohit@example.com,Good,264.0
5,S006,agastya,95.0,92.0,92,NaN,A,4321098765,agastya@example.com,Excellent,279.0
6,S007,amar,80.0,NaN,84,84.0,C,3210987654,amar@example.com,Average,NaN
7,S008,joy,91.0,89.0,89,89.0,A,2109876543,joy@example.com,Good,269.0
8,S009,Rohit,89.0,90.0,90,90.0,A,1098765432,rohit@example.com,Excellent,269.0
9,S010,Mahi,94.0,40.0,40,40.0,C,0987654321,mahi@example.com,Average,174.0
10,S011,Jhanvi,87.0,56.0,56,56.0,B,9876543210,jhanvi@example.com,Good,199.0
11,S012,Shubham,90.0,78.0,78,78.0,B,8765432109,shubham@example.com,Good,246.0
12,S013,Priya,85.0,85.0,85,85.0,B,7654321098,priya@example.com,Good,255.0
13,S014,Anit,88.0,90.0,90,90.0,A,6543210987,anit@example.com,Excellent,268.0
14,S015,Rahul,92.0,30.0,30,30.0,A,5432109876,rahul@example.com,Excellent,152.0

In [797]:
df.drop("Total",axis=1)
df["Science"].fillna(df["Science"].mean(),inplace=True)

# i want to convert the Science column to int type after filling the missing values with mean

df["Science"]=df["Science"].astype("int64")

df["Maths"].fillna(df["Maths"].mean(),inplace=True)
df["Maths"]=df["Maths"].astype("int64")
df

C:\Users\hp\AppData\Local\Temp\ipykernel_5680\2575043407.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Science"].fillna(df["Science"].mean(),inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_5680\2575043407.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Maths"].fillna(df["Maths"].mean(),inplace=True)

,StudentId,Name,Maths,Science,English,Attendance,Grade,Phone,Email,Remarks,Total
0,S001,Alice,85,80,75,90.0,A,8989657890,alice@example.com,Excellent,240.0
1,S002,Bob,90,85,80,85.0,A,9876543210,bob@example.com,Excellent,255.0
2,S003,Charlie,89,90,85,95.0,B,7654321098,charlie@example.com,Good,NaN
3,S004,David,92,76,90,80.0,A,6543210987,david@example.com,Excellent,NaN
4,S005,rohit,88,88,88,88.0,A,5432109876,rohit@example.com,Good,264.0
5,S006,agastya,95,92,92,NaN,A,4321098765,agastya@example.com,Excellent,279.0
6,S007,amar,80,76,84,84.0,C,3210987654,amar@example.com,Average,NaN
7,S008,joy,91,89,89,89.0,A,2109876543,joy@example.com,Good,269.0
8,S009,Rohit,89,90,90,90.0,A,1098765432,rohit@example.com,Excellent,269.0
9,S010,Mahi,94,40,40,40.0,C,0987654321,mahi@example.com,Average,174.0
10,S011,Jhanvi,87,56,56,56.0,B,9876543210,jhanvi@example.com,Good,199.0
11,S012,Shubham,90,78,78,78.0,B,8765432109,shubham@example.com,Good,246.0
12,S013,Priya,85,85,85,85.0,B,7654321098,priya@example.com,Good,255.0
13,S014,Anit,88,90,90,90.0,A,6543210987,anit@example.com,Excellent,268.0
14,S015,Rahul,92,30,30,30.0,A,5432109876,rahul@example.com,Excellent,152.0

#### Data Cleaning

In [798]:
import pandas as pd
import numpy as np

from datetime import datetime # this is the module to work with date and time in python

In [ ]:
df=pd.DataFrame({
    "CustomerName":["Priyvrat","Rahul Sharma             ","priya patel","AMIT KUMAR","neha gupta"," Vikas Jain","priya patel","sneha reddy"," rahul sharma ","Pooja Mehta",None,"Priyvrat"],
    "OrderDate":["2023-08-25","2023-01-15","2023/02/20","2023-03-10","20-04-2025","2023-05-25","2023-06-30","2023-07-15","2023-08-20","20-09-2010",None,"2023-08-25"],
    "ProductName":["Mouse","Laptop","Mobile","Keyboard","Headphones","Mouse","Mouse","Printer","Monitor","Keyboard","Mouse","Mouse"],
    "Quantity":["2",'1','2','koko','1','-3','2','1','1','2','200',"2"],
    "Price":[20000,50000,20000,1500,3000,800,800,5000,10000,1500,800,20000],
    "City":["Lucknow","Mumbai","Delhi","Chicago","Kolkata","Hongkong","Delhi","Mumbai","Kolkata","Delhi","Pune","Lucknow"],
    "DeliveryDate":["2023-08-25","2023-01-20","2023/02/25","2023-03-15","25-04-2025","2023-05-30","2023-07-05","2023-07-20","2023-08-25","2023-09-20","2023-08-25","2023-08-25"]
})
print(df)

                 CustomerName   OrderDate ProductName Quantity  Price  \
0                    Priyvrat  2023-08-25       Mouse        2  20000
1   Rahul            Sharma    2023-01-15      Laptop        1  50000
2                 priya patel  2023/02/20      Mobile        2  20000
3                  AMIT KUMAR  2023-03-10    Keyboard     koko   1500
4                  neha gupta  20-04-2025  Headphones        1   3000
5                  Vikas Jain  2023-05-25       Mouse       -3    800
6                 priya patel  2023-06-30       Mouse        2    800
7                 sneha reddy  2023-07-15     Printer        1   5000
8               rahul sharma   2023-08-20     Monitor        1  10000
9                 Pooja Mehta  20-09-2010    Keyboard        2   1500
10                       None        None       Mouse      200    800
11                   Priyvrat  2023-08-25       Mouse        2  20000

        City DeliveryDate
0    Lucknow   2023-08-25
1     Mumbai   2023-01-20
2      Delhi   2023/02/25
3    Chicago   2023-03-15
4    Kolkata   25-04-2025
5   Hongkong   2023-05-30
6      Delhi   2023-07-05
7     Mumbai   2023-07-20
8    Kolkata   2023-08-25
9      Delhi   2023-09-20
10      Pune   2023-08-25
11   Lucknow   2023-08-25

In [800]:
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerName  11 non-null     object
 1   OrderDate     11 non-null     object
 2   ProductName   12 non-null     object
 3   Quantity      12 non-null     object
 4   Price         12 non-null     int64
 5   City          12 non-null     object
 6   DeliveryDate  12 non-null     object
dtypes: int64(1), object(6)
memory usage: 800.0+ bytes

CustomerName    1
OrderDate       1
ProductName     0
Quantity        0
Price           0
City            0
DeliveryDate    0
dtype: int64

In [801]:
print(df.duplicated().sum()) # it will return the count of duplicate rows in the data frame

1

In [825]:
df["CustomerName"]=df["CustomerName"].str.strip()# this will remove the leading and trailing spaces and convert the first letter of each word to uppercase and rest to lowercase in the CustomerName column
df["CustomerName"]=df["CustomerName"].str.capitalize() # this will convert the first letter of each word to uppercase and rest to lowercase in the CustomerName column
df.dropna(inplace=True) # this will drop the rows which have missing values in any column
print(df)

               CustomerName   OrderDate ProductName Quantity  Price      City  \
0                  Priyvrat  2023-08-25       Mouse        2  20000   Lucknow
1   Rahul            sharma  2023-01-15      Laptop        1  50000    Mumbai
2               Priya patel  2023/02/20      Mobile        2  20000     Delhi
3                Amit kumar  2023-03-10    Keyboard     koko   1500   Chicago
4                Neha gupta  20-04-2025  Headphones        1   3000   Kolkata
5                Vikas jain  2023-05-25       Mouse       -3    800  Hongkong
6               Priya patel  2023-06-30       Mouse        2    800     Delhi
7               Sneha reddy  2023-07-15     Printer        1   5000    Mumbai
8              Rahul sharma  2023-08-20     Monitor        1  10000   Kolkata
9               Pooja mehta  20-09-2010    Keyboard        2   1500     Delhi
11                 Priyvrat  2023-08-25       Mouse        2  20000   Lucknow

   DeliveryDate
0    2023-08-25
1    2023-01-20
2    2023/02/25
3    2023-03-15
4    25-04-2025
5    2023-05-30
6    2023-07-05
7    2023-07-20
8    2023-08-25
9    2023-09-20
11   2023-08-25

In [803]:
df["City"]=df["City"].replace({"Chicago":"Goa","Hongkong":"Hyderabad"})
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
1,Rahul sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-20
2,Priya patel,2023/02/20,Mobile,2,20000,Delhi,2023/02/25
3,Amit kumar,2023-03-10,Keyboard,koko,1500,Goa,2023-03-15
4,Neha gupta,20-04-2025,Headphones,1,3000,Kolkata,25-04-2025
5,Vikas jain,2023-05-25,Mouse,-3,800,Hyderabad,2023-05-30
6,Priya patel,2023-06-30,Mouse,2,800,Delhi,2023-07-05
7,Sneha reddy,2023-07-15,Printer,1,5000,Mumbai,2023-07-20
8,Rahul sharma,2023-08-20,Monitor,1,10000,Kolkata,2023-08-25
9,Pooja mehta,20-09-2010,Keyboard,2,1500,Delhi,2023-09-20
11,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25

In [804]:
def parseDate(datestr):
    if pd.isna(datestr):
        return pd.NaT
    
    datestr=str(datestr).strip()

    formats=['%Y-%m-%d','%Y/%m/%d','%d-%m-%Y','%Y-%d-%m',"%d/%m/%Y","%Y-%m-%d","%Y/%m/%d","%d-%m-%Y","%Y-%d-%m", "%d/%m/%Y"]

    for fmt in formats:
        try:
            return pd.to_datetime(datestr, format=fmt)
        except :
            continue
    return pd.NaT

df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
1,Rahul sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-20
2,Priya patel,2023/02/20,Mobile,2,20000,Delhi,2023/02/25
3,Amit kumar,2023-03-10,Keyboard,koko,1500,Goa,2023-03-15
4,Neha gupta,20-04-2025,Headphones,1,3000,Kolkata,25-04-2025
5,Vikas jain,2023-05-25,Mouse,-3,800,Hyderabad,2023-05-30
6,Priya patel,2023-06-30,Mouse,2,800,Delhi,2023-07-05
7,Sneha reddy,2023-07-15,Printer,1,5000,Mumbai,2023-07-20
8,Rahul sharma,2023-08-20,Monitor,1,10000,Kolkata,2023-08-25
9,Pooja mehta,20-09-2010,Keyboard,2,1500,Delhi,2023-09-20
11,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25

In [805]:
df["OrderDate"]=df["OrderDate"].apply(parseDate)
df["DeliveryDate"]=df["DeliveryDate"].apply(parseDate)
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25
1,Rahul sharma,2023-01-15,Laptop,1,50000,Mumbai,2023-01-20
2,Priya patel,2023-02-20,Mobile,2,20000,Delhi,2023-02-25
3,Amit kumar,2023-03-10,Keyboard,koko,1500,Goa,2023-03-15
4,Neha gupta,2025-04-20,Headphones,1,3000,Kolkata,2025-04-25
5,Vikas jain,2023-05-25,Mouse,-3,800,Hyderabad,2023-05-30
6,Priya patel,2023-06-30,Mouse,2,800,Delhi,2023-07-05
7,Sneha reddy,2023-07-15,Printer,1,5000,Mumbai,2023-07-20
8,Rahul sharma,2023-08-20,Monitor,1,10000,Kolkata,2023-08-25
9,Pooja mehta,2010-09-20,Keyboard,2,1500,Delhi,2023-09-20
11,Priyvrat,2023-08-25,Mouse,2,20000,Lucknow,2023-08-25

In [808]:
df["Quantity"]=pd.to_numeric(df["Quantity"],errors="coerce")  ## here we have converted the Quantity column to numeric type and if there is any error in conversion it will be replaced with NaN
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2.0,20000,Lucknow,2023-08-25
1,Rahul sharma,2023-01-15,Laptop,1.0,50000,Mumbai,2023-01-20
2,Priya patel,2023-02-20,Mobile,2.0,20000,Delhi,2023-02-25
3,Amit kumar,2023-03-10,Keyboard,NaN,1500,Goa,2023-03-15
4,Neha gupta,2025-04-20,Headphones,1.0,3000,Kolkata,2025-04-25
5,Vikas jain,2023-05-25,Mouse,-3.0,800,Hyderabad,2023-05-30
6,Priya patel,2023-06-30,Mouse,2.0,800,Delhi,2023-07-05
7,Sneha reddy,2023-07-15,Printer,1.0,5000,Mumbai,2023-07-20
8,Rahul sharma,2023-08-20,Monitor,1.0,10000,Kolkata,2023-08-25
9,Pooja mehta,2010-09-20,Keyboard,2.0,1500,Delhi,2023-09-20
11,Priyvrat,2023-08-25,Mouse,2.0,20000,Lucknow,2023-08-25

In [822]:
print("Now we are going to check for the negative vaues in Quantity column")

df[df["Quantity"]<0]

df["Quantity"]=df["Quantity"].abs() # this will convert the negative values in Quantity column to positive values
df

Now we are going to check for the negative vaues in Quantity column

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Priyvrat,2023-08-25,Mouse,2.0,20000,Lucknow,2023-08-25
1,Rahul sharma,2023-01-15,Laptop,1.0,50000,Mumbai,2023-01-20
2,Priya patel,2023-02-20,Mobile,2.0,20000,Delhi,2023-02-25
3,Amit kumar,2023-03-10,Keyboard,NaN,1500,Goa,2023-03-15
4,Neha gupta,2025-04-20,Headphones,1.0,3000,Kolkata,2025-04-25
5,Vikas jain,2023-05-25,Mouse,3.0,800,Hyderabad,2023-05-30
6,Priya patel,2023-06-30,Mouse,2.0,800,Delhi,2023-07-05
7,Sneha reddy,2023-07-15,Printer,1.0,5000,Mumbai,2023-07-20
8,Rahul sharma,2023-08-20,Monitor,1.0,10000,Kolkata,2023-08-25
9,Pooja mehta,2010-09-20,Keyboard,2.0,1500,Delhi,2023-09-20
11,Priyvrat,2023-08-25,Mouse,2.0,20000,Lucknow,2023-08-25