### what is Scaling  and StandardScaler Class in Sklearn 
### The Algorithms  that requires the Scaling are as follows :
#### 1. Linear Regression 
#### 2. Logistic Regression 
#### 3. Ridge Regression 
#### 4. Lasso Regression 
#### 5. KNN
#### 6. SVM
#### 7. Neural Networks

In [4]:
import pandas as pd 
import numpy as np 

df=pd.DataFrame({
    "Age":[25,30,35,45,60,54,65,62,40,50],
    "Exp":[2,5,10,17,22,20,25,21,15,19],
    "Salary":[40000,64000,83000,110000,20000,45000,60000,560000,48000,150000]
})
df

   Age  Exp  Salary
0   25    2   40000
1   30    5   64000
2   35   10   83000
3   45   17  110000
4   60   22   20000
5   54   20   45000
6   65   25   60000
7   62   21  560000
8   40   15   48000
9   50   19  150000

In [11]:
mean=df["Age"].mean()
mean ## 46.6 
std=df["Age"].std()
data=df["Age"]-mean  ## we are finding distance from the mean 
data
std

13.922004964164543

In [13]:
df["Age"]=data/std

df["Age"]
# -3 to 3

0   -1.551501
1   -1.192357
2   -0.833213
3   -0.114926
4    0.962505
5    0.531533
6    1.321649
7    1.106163
8   -0.474070
9    0.244218
Name: Age, dtype: float64

In [ ]:
mean_val=df["Exp"].mean()
std_val=df["Exp"].std()

df["Exp"]=(df["Exp"]-mean_val)/std_val
df["Exp"]

df

# scaling formula is  Z=(x-mean/std)

# -3  to  +3

        Age       Exp  Salary
0 -1.551501 -1.788511   40000
1 -1.192357 -1.393986   64000
2 -0.833213 -0.736446   83000
3 -0.114926  0.184111  110000
4  0.962505  0.841652   20000
5  0.531533  0.578636   45000
6  1.321649  1.236176   60000
7  1.106163  0.710144  560000
8 -0.474070 -0.078905   48000
9  0.244218  0.447128  150000

In [23]:
df=pd.read_csv("fueldata.csv")
df=df.rename(columns={"Fuel Consumption City (L/100 km)":"A","Fuel Consumption Hwy (L/100 km)":"B",
                   "Fuel Consumption Comb (L/100 km)":"C","Fuel Consumption Comb (mpg)":"D"})
df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,A,B,C,D,CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [32]:
mean_value=df[["A","B","C","D"]].mean()
mean_value
std_value=df[["A","B","C","D"]].std()
std_value

df[["A","B","C","D"]]=(df[["A","B","C","D"]]-mean_value)/std_value
df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,A,B,C,D,CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,-0.758950,-1.052709,-0.855684,0.763059,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,-0.387551,-0.603161,-0.475391,0.209952,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,-1.873149,-1.457303,-1.754558,2.837208,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,0.040987,0.026206,0.043191,-0.343155,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,-0.130428,-0.153613,-0.129670,-0.066601,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,-0.530397,-0.603161,-0.544535,0.348229,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,-0.387551,-0.333433,-0.371675,0.209952,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,-0.244705,-0.198568,-0.233386,-0.066601,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,-0.387551,-0.333433,-0.371675,0.209952,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,-0.101859,-0.153613,-0.095098,-0.204878,248

#### Polynomial Regression - Polynomial regression is a ML technique that models curved relationship by creating the additional  features  for  x**2  X**3 X**4

#### Y = mx + c  - equations for linear regression 

#### polynom Reg -->  y=c+ m1*X +m2*X**2 + m3*X**3

#### Ridge Regression 
Area        Bedrooms        parking     garden       price 
1000        3                  2            1         50L
1500        4                  2            2         75L


Price=20000*Area + 150000*Bedrooms + 90000*garden +500000*parking  ## This was original equation
Price=2000*Area+ 15000*Bedroms +9000*garden +50000*parking  ## here we have shrinked the coef of all features

#### Example code of Ridge Regressions 

from  sklearn.linear_model import Ridge 

model=Ridge(alpha=1000) ## alpha is he penalty strength to shring the coef of the features 

model.fit()

In [71]:
from sklearn.linear_model import Ridge 
from sklearn.metrics import r2_score


df=pd.read_csv("fueldata.csv")

features=df[['Engine Size(L)',
 'Cylinders',
 'Fuel Consumption City (L/100 km)',
 'Fuel Consumption Hwy (L/100 km)',
 'Fuel Consumption Comb (L/100 km)',
 'Fuel Consumption Comb (mpg)']]

X=features
Y=df['CO2 Emissions(g/km)'] # response 



model=Ridge(alpha=100000) ## alpha is he penalty strength to shring the coef of the features 

model.fit(X,Y)

Ridge(alpha=100000)

In [72]:
for col , coef in zip(X.columns,model.coef_):
    print(col,coef)

Engine Size(L) 1.1406296295061884
Cylinders 1.6020215708751857
Fuel Consumption City (L/100 km) 2.2060064391813072
Fuel Consumption Hwy (L/100 km) 1.3359476376128312
Fuel Consumption Comb (L/100 km) 1.8146822966115448
Fuel Consumption Comb (mpg) -3.861262488044159

#### Lasso Regression Technique - in Lasso regressions it removes the unimport features by making their coef zero 
#### while feature selection


Area        Bedrooms        Paintcolor     garden     price  nearbyairport
1000        3                  0            1         50L       1
1500        4                  1            2         75L       0


to predict the price of the house only three columns are imp 
ie 
1 Area 2 Bedrooms 3 Garden   but the other two paintcolor and nearbyairpot are not the imp ones

In [64]:
from sklearn.linear_model import Lasso 
from sklearn.metrics import r2_score


df=pd.read_csv("fueldata.csv")

features=df[['Engine Size(L)',
 'Cylinders',
 'Fuel Consumption City (L/100 km)',
 'Fuel Consumption Hwy (L/100 km)',
 'Fuel Consumption Comb (L/100 km)',
 'Fuel Consumption Comb (mpg)']]

X=features
Y=df['CO2 Emissions(g/km)']

In [46]:
df.columns.tolist()
features=df[['Engine Size(L)',
 'Cylinders',
 'Fuel Consumption City (L/100 km)',
 'Fuel Consumption Hwy (L/100 km)',
 'Fuel Consumption Comb (L/100 km)',
 'Fuel Consumption Comb (mpg)']]

X=features
Y=df['CO2 Emissions(g/km)']

In [79]:
my_model=Lasso()
my_model.fit(X,Y)

Lasso()

In [80]:
for col , coef in zip(X.columns,my_model.coef_):
    print(col,coef)

Engine Size(L) 3.3611305821473842
Cylinders 7.815851803613851
Fuel Consumption City (L/100 km) 1.5784861167950037
Fuel Consumption Hwy (L/100 km) 4.231618836348186
Fuel Consumption Comb (L/100 km) 0.0015747696274906933
Fuel Consumption Comb (mpg) -3.5563862454539357